version: '3.9'
services:
  api:
    environment:
      - API_PORT=${API_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - API_PORT=${API_PORT}
        - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - "9000:9000"
  client:
    environment:
      - API_PORT=${API_PORT}
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - API_PORT=${API_PORT}
    ports:
      - "3000:3000"