version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "9000:9000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"